name: Build and release

on:
    push:
        tags:
            - 'v*.*.*'
            - 'v*.*.*-rc.*'
        
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Node dependencies
              run: npm install

            - name: Package plugin
              run: ./node_modules/.bin/wp-scripts plugin-zip

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ucsc-communications-functionality.zip
                  generate_release_notes: true